name: JoyQueue Kafka
driverClass: io.openmessaging.benchmark.driver.kafka.JoyQueueKafkaBenchmarkDriver

# Kafka client-specific configuration
replicationFactor: 3

topicConfig: |
  min.insync.replicas=2

commonConfig: |
  bootstrap.servers=192.169.0.2:50088
  naming.servers=192.169.0.2:50091

producerConfig: |
  acks=all
  linger.ms=1
  batch.size=131072

consumerConfig: |
  auto.offset.reset=earliest
  enable.auto.commit=false
